import "./globals.css";
import localFont from "next/font/local";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'; 
import AppWalletProvider from "@/app/components/wallet/AppWalletProvider";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer"
import { AppProvider } from './context/context';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppWalletProvider>
            <AppProvider>
                <Navbar />
                {children}
            </AppProvider>
        </AppWalletProvider>
        <Footer />

        <ToastContainer />

      </body>
    </html>
  );
}
